/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blaze.persistence.starter;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
class AppTest {
    @Test
    void smoke() {
        assertThat(true).isTrue();
    }
}
